name: umbra_core

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "packages/umbra_core/**"
      - ".github/workflows/umbra_core.yaml"

  pull_request:
    paths:
      - "packages/umbra_core/**"
      - ".github/workflows/umbra_core.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/umbra_core
      flutter_channel: stable
      flutter_version: 2.10.0
